name: 'Terraform Plan'

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: cd cluster && terraform init

    - name: Terraform Plan
      run: cd cluster && terraform plan -no-color -out=plan.txt

    - name: Output Plan
      run: cat cluster/plan.txt